Repository Vikash-8090-Yadav/SaL--dApp, pull requests merged in 2023-06, with the labels that each got.

#148 Improved Card, Button Style and Navbar
  Component/Card.js
  Component/Layout.js
  Component/LogoutButton.js
  Component/Navbar.js
Labels: gssoc23, Level1, Ready-To-Merge

#153 Added a Design folder + Figma file containing the new Sall-Dapp design
  design/Sal-Dapp.fig
  design/maindesign.md
Labels: gssoc23, Level3

#154 Tech badges
  README.md
Labels: gssoc23, Level1, Ready-To-Merge

#106 Added scroll to top option
  Component/GoToTop.js
  Component/Layout.js
Labels: gssoc23, Level1, Ready-To-Merge

#166 Fix Issue#159 Redesign the Footer
  Component/images/footer-icon.png
  Component/v1.0.0/footer/footer.jsx
  styles/globals.css
  tailwind.config.js
Labels: enhancement, gssoc23, Level3

#163 Resolved the bug of Google Github Button
  pages/_app.js
Labels: question, gssoc23, level2, Ready-To-Merge

#169 Centered Take Help Section
  Component/Contact.js
Labels: bug, gssoc23, level2, Ready-To-Merge
