Repository Vikash-8090-Yadav/SaL--dApp, pull requests merged in 2023-05, with the labels that each got.

#36 changes in the cursor of heading from default to arrow and also chang…
  Component/Navbar.js
Labels: GSSoc23, Level1, Ready-To-Merge

#59 Update README.md
  README.md
Labels: documentation, GSSoc23, Level1, Ready-To-Merge

#69 Fixed tailwind CSS spelling
  README.md
Labels: documentation, GSSoc23, Level1, Ready-To-Merge

#76 Added Contributing members section as per #issue72
  README.md
Labels: gssoc23, Level1, Ready-To-Merge

#90 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: gssoc23, Level1, Ready-To-Merge

#103 Solved requested changes
  README.md
Labels: gssoc23, Level1, Ready-To-Merge

#113 Add a Github Action for the Automatic Reviewers #96
  .github/auto_assign.yml
  .github/workflows/action.yml
Labels: good first issue, gssoc23, Level1

#57 Added issue template and pull request template
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/custom.yml
  .github/ISSUE_TEMPLATE/doc_improve.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/pr_request.md
Labels: Changes-Requested

#144 Added a new Header image for README.md
  README.md
Labels: gssoc23, Level2

#122 I have successfully added refresh functionality to Home button :) #117
  Component/Navbar.js
Labels: Ready-To-Merge
